version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "unicorn-location-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cgbyrg19wrd4"
s3_prefix = "unicorn-location-api"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Prod\" SnapStart=\"PublishedVersions\""
image_repositories = []