AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  unicorn-location-workshop

  Sample SAM Template for unicorn-location-workshop

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Layers: 
      - !Ref UnicornLocationLambdaLayer
    MemorySize: 1024

Resources:
  UnicornLocationLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: unicorn-location-lambda-layer
      ContentUri: UnicornLocationLambdaLayer
      CompatibleRuntimes:
        - java11
    Metadata:
      BuildMethod: java11

  UnicornLocationTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: unicorn-locations

  UnicornLocationApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "unicorn-location-api"
      StageName: Prod
      
  UnicornLocationPostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: UnicornLocationFunction
      FunctionName: unicorn-location-api-post
      Handler: com.unicorn.location.UnicornPostLocationHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref UnicornLocationTable
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /locations
            Method: post
            RestApiId: !Ref UnicornLocationApi
    Metadata:
      BuildMethod: makefile

  UnicornLocationGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: UnicornLocationFunction
      FunctionName: unicorn-location-api-get
      Handler: com.unicorn.location.UnicornGetLocationHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UnicornLocationTable
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        IdEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /locations/{id}
            Method: get
            RestApiId: !Ref UnicornLocationApi
        AllEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /locations
            Method: get
            RestApiId: !Ref UnicornLocationApi

            
    Metadata:
      BuildMethod: makefile


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UnicornLocationApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${UnicornLocationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/locations/"
  UnicornLocationPostFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt UnicornLocationPostFunction.Arn
  UnicornLocationPostFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UnicornLocationPostFunctionRole.Arn
